swagger: '2.0'
info:
  title: return-everything
  version: 1.0.0
  description: |
    It returns environment variables, HTTP request headers and so on.
consumes:
  - application/json
produces:
  - application/json
schemes:
  - http
host: localhost
paths:
  /:
    get:
      description: |
        returns everything
      operationId: getEverything
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Everything'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /app:
    get:
      description: |
        returns application information
      operationId: getApp
      tags:
        - application
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Application'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  '/app/{key}':
    get:
      description: |
        returns application specified information
      operationId: getAppField
      tags:
        - application
      parameters:
        - name: key
          in: path
          description: Can specify a field
          required: true
          type: string
          enum:
            - args
            - grp
            - user
            - workdir
      responses:
        '200':
          description: OK
          schema:
            type: string
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /app/envs:
    get:
      description: |
        returns environment variables
      operationId: getAppEnvs
      tags:
        - application
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              type: string
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  '/app/envs/{env}':
    get:
      description: |
        returns an environment variable
      operationId: getAppEnv
      tags:
        - application
      parameters:
        - name: env
          in: path
          description: Can specify an environment variable
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: string
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /host:
    get:
      description: |
        returns host information
      operationId: getHost
      tags:
        - host
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Host'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  '/host/{key}':
    get:
      description: |
        returns host specified information
      operationId: getHostField
      tags:
        - host
      parameters:
        - name: key
          in: path
          description: Can specify a field
          required: true
          type: string
          enum:
            - name
            - hosts
            - resolv_conf
      responses:
        '200':
          description: OK
          schema:
            type: object
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /req:
    get:
      description: |
        returns HTTP request information
      operationId: getRequestInfo
      tags:
        - request
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/HTTPRequest'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  '/req/{key}':
    get:
      description: |
        returns HTTP request specified information
      operationId: getRequestField
      tags:
        - request
      parameters:
        - name: key
          in: path
          description: Can specify a field
          required: true
          type: string
          enum:
            - protocol
            - method
            - host
            - remote_addr
            - uri
      responses:
        '200':
          description: OK
          schema:
            type: string
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /req/headers:
    get:
      description: |
        returns HTTP request headers
      operationId: getRequestHeaders
      tags:
        - request
      responses:
        '200':
          description: OK
          schema:
            type: object
            additionalProperties:
              type: array
              items:
                type: string
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  '/req/headers/{header}':
    get:
      description: |
        returns a specified HTTP request header
      operationId: getRequestHeader
      tags:
        - request
      parameters:
        - name: header
          in: path
          description: Can specify an header
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              type: string
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /req/form:
    get:
      description: |
        returns HTTP GET query parameters and the POST / PUT form data
      operationId: getRequestForm
      tags:
        - request
      responses:
        '200':
          description: OK
          schema:
            type: object
            additionalProperties:
              type: array
              items:
                type: string
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /req/post_form:
    get:
      description: |
        returns form data including only HTTP POST, PATCH or PUT body parameters
      operationId: getRequestPostForm
      tags:
        - request
      responses:
        '200':
          description: OK
          schema:
            type: object
            additionalProperties:
              type: array
              items:
                type: string
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  Everything:
    description: application context
    required:
      - app
      - host
      - req
    properties:
      app:
        $ref: '#/definitions/Application'
      host:
        $ref: '#/definitions/Host'
      req:
        $ref: '#/definitions/HTTPRequest'
  Application:
    description: Application information
    required:
      - args
      - envs
      - grp
      - user
      - workdir
    properties:
      args:
        description: Application's arguments
        type: array
        items:
          type: string
      envs:
        description: Environment variables
        type: array
        items:
          type: string
      workdir:
        description: Working directory
        type: string
      grp:
        description: The group ID of the calling process
        type: integer
        format: int64
      user:
        description: The user ID of the calling process
        type: integer
        format: int64
  Host:
    description: Host information
    required:
      - name
      - hosts
      - resolv_conf
    properties:
      name:
        description: Host name
        type: string
      hosts:
        description: /etc/hosts
        type: array
        items:
          type: string
      resolv_conf:
        description: /etc/resolv.conf
        type: array
        items:
          type: string
  HTTPRequest:
    description: HTTP request information
    required:
      - protocol
      - method
      - host
      - remote_addr
      - uri
      - headers
      - form
      - post_form
    properties:
      protocol:
        description: HTTP Protocol
        type: string
      method:
        description: HTTP Method
        type: string
        enum:
          - get
      host:
        description: Host
        type: string
      remote_addr:
        description: Remote address
        type: string
      uri:
        description: URI
        type: string
        pattern: >-
          ^((http[s]?):\/)?\/?([^:\/\s]+)((\/\w+)*\/)([\w\-\.]+[^#?\s]+)(.*)?(#[\w\-]+)?$
      headers:
        description: HTTP request headers
        type: object
        additionalProperties:
          type: array
          items:
            type: string
      form:
        description: HTTP GET query parameters and the POST / PUT form data
        type: object
        additionalProperties:
          type: array
          items:
            type: string
      post_form:
        description: 'Including only HTTP POST, PATCH or PUT body parameters'
        type: object
        additionalProperties:
          type: array
          items:
            type: string
  Error:
    required:
      - code
      - message
    properties:
      code:
        type: string
      message:
        type: string
