version: "2.4"

services:
  editor:
    image: swaggerapi/swagger-editor:v3.14.8
    ports:
      - 9000:8080
    environment:
      - SWAGGER_FILE=/spec/spec.yaml
    volumes:
      - ..:/spec
    container_name: editor
