version: "2"

services:
  # docker-compose -f dev/runtime.yml up
  api:
    image: golang:1.15.6-alpine3.12
    command: go run generated/cmd/return-everything-server/main.go --host 0.0.0.0 --port 8080
    ports:
      - 9000:8080
    volumes:
      - ..:/go/src/github.com/pottava/http-return-everything
    environment:
      - ACCESS_LOG
      - ACCESS_DETAIL_LOG
      - CONTENT_ENCODING
    working_dir: /go/src/github.com/pottava/http-return-everything/app
    container_name: api
