version: "2.1"

services:
  # docker-compose -f dev/tools.yml run --rm codegen
  codegen:
    image: supinf/go-swagger:0.12
    command: generate server -f spec.yaml -t app/generated
    volumes:
      - ..:/go/src/github.com/pottava/http-return-everything
    working_dir: /go/src/github.com/pottava/http-return-everything

  # docker-compose -f dev/tools.yml run --rm deps
  deps:
    image: supinf/go-dep:0.3
    command: ensure
    volumes:
      - ..:/go/src/github.com/pottava/http-return-everything
    working_dir: /go/src/github.com/pottava/http-return-everything/app

  # docker-compose -f dev/tools.yml run --rm test
  test:
    image: pottava/golang:1.9
    command: sh -c "go test -cover -bench -benchmem `go list ./... | grep -v /generated/` -v"
    volumes:
      - ..:/go/src/github.com/pottava/http-return-everything
    working_dir: /go/src/github.com/pottava/http-return-everything/app

  # BUILD_VERSION=v0.1.0 BUILD_DATE=`date +%FT%T%z` docker-compose -f dev/tools.yml run --rm build
  build:
    image: pottava/gox:go1.8
    command: --osarch "linux/amd64 darwin/amd64 windows/amd64" -ldflags "-X main.version=${BUILD_VERSION} -X main.date=${BUILD_DATE}" -output "/go/src/github.com/pottava/http-return-everything/dist/{{.OS}}_{{.Arch}}"
    volumes:
      - ..:/go/src/github.com/pottava/http-return-everything
    working_dir: /go/src/github.com/pottava/http-return-everything/app/generated/cmd/return-everything-server
