version: "2.1"

services:
  # docker-compose -f dev/tools.yml run --rm codegen
  codegen:
    image: supinf/go-swagger:0.16.0
    command: generate server -f spec.yaml -t app/generated
    volumes:
      - ..:/go/src/github.com/pottava/http-return-everything
    working_dir: /go/src/github.com/pottava/http-return-everything

  # docker-compose -f dev/tools.yml run --rm vendor
  vendor:
    image: golangci/golangci-lint:v1.33.0-alpine
    command: go mod vendor
    volumes:
      - ..:/go/src/github.com/pottava/http-return-everything
    working_dir: /go/src/github.com/pottava/http-return-everything/app

  # docker-compose -f dev/tools.yml run --rm lint
  lint:
    image: golangci/golangci-lint:v1.33.0-alpine
    command: golangci-lint run --config .golangci.yml
    volumes:
      - ..:/go/src/github.com/pottava/http-return-everything
    working_dir: /go/src/github.com/pottava/http-return-everything/app

  # docker-compose -f dev/tools.yml run --rm test
  test:
    image: golangci/golangci-lint:v1.33.0-alpine
    command: sh -c "go test -cover -bench -benchmem `go list ./... | grep -v /generated/` -v"
    volumes:
      - ..:/go/src/github.com/pottava/http-return-everything
    working_dir: /go/src/github.com/pottava/http-return-everything/app
